import { createFileRoute, Link } from "@tanstack/react-router";
import { PageLayout } from "@/components/PageLayout";
import { Section, Eyebrow } from "@/components/Section";
import { Target, Compass, Globe2, HeartHandshake } from "lucide-react";

export const Route = createFileRoute("/about")({ head: () => ({ meta: [{ title: "About — Dime Consultants" }, { name: "description", content: "Dime Consultants is an AI and Business Process Reengineering firm based at Two Rivers Mall, Nairobi. We serve clients across all industries." }] }), component: AboutPage });

function AboutPage() {
  return <PageLayout><Section><Eyebrow>About us</Eyebrow><h1 className="page-title">We help organisations turn intelligence into outcomes.</h1><p className="page-copy">Dime Consultants Limited is an AI and Business Process Reengineering consultancy headquartered at Two Rivers Mall, Nairobi. We work with leaders across every sector — financial services, logistics, healthcare, manufacturing, public sector and more — to design, train and deploy AI capability that produces measurable ROI.</p><div className="responsive-grid three about-principles">{[{ i: Target, t: "Mission", d: "Make modern AI practical, ethical and ROI-positive for every workforce we touch." }, { i: Compass, t: "Vision", d: "An East Africa where every organisation operates with intelligent systems by default." }, { i: HeartHandshake, t: "Values", d: "Craft, candour, compounding outcomes — and respect for the contexts we operate in." }].map((x) => <div key={x.t} className="card about-card"><x.i className="cyan-icon" /><h3>{x.t}</h3><p>{x.d}</p></div>)}</div></Section><section className="split-band"><div className="band-grid two"><div><Globe2 className="cyan-icon" /><h2 className="section-title">Rooted in Nairobi. Built for the world.</h2><p className="about-band-copy">Our work spans East Africa and beyond — from global multinationals refining their finance operations, to regional banks navigating digital transformation, to mission-driven organisations using AI to scale impact. Every engagement is tailored. None is templated.</p></div><div className="metric-grid">{[["12+", "Industries served"], ["3", "Continents reached"], ["500+", "Practitioners trained"], ["90 days", "Average ROI horizon"]].map(([v, l]) => <div key={l} className="card metric-card"><div className="metric-value gradient-text">{v}</div><div className="metric-label">{l}</div></div>)}</div></div></section><Section className="about-cta"><h2 className="section-title">Let's design your transformation.</h2><Link to="/contact" className="button-primary">Talk to us</Link></Section></PageLayout>;
}
