/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as UseCasesRouteImport } from './routes/use-cases';
import { Route as SuccessStoriesRouteImport } from './routes/success-stories';
import { Route as ServicesRouteImport } from './routes/services';
import { Route as ScannerRouteImport } from './routes/scanner';
import { Route as ProgrammeRouteImport } from './routes/programme';
import { Route as InsightsRouteImport } from './routes/insights';
import { Route as ContactRouteImport } from './routes/contact';
import { Route as AboutRouteImport } from './routes/about';
import { Route as IndexRouteImport } from './routes/index';
const UseCasesRoute = UseCasesRouteImport.update({
    id: '/use-cases',
    path: '/use-cases',
    getParentRoute: () => rootRouteImport,
});
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
    id: '/success-stories',
    path: '/success-stories',
    getParentRoute: () => rootRouteImport,
});
const ServicesRoute = ServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => rootRouteImport,
});
const ScannerRoute = ScannerRouteImport.update({
    id: '/scanner',
    path: '/scanner',
    getParentRoute: () => rootRouteImport,
});
const ProgrammeRoute = ProgrammeRouteImport.update({
    id: '/programme',
    path: '/programme',
    getParentRoute: () => rootRouteImport,
});
const InsightsRoute = InsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => rootRouteImport,
});
const ContactRoute = ContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => rootRouteImport,
});
const AboutRoute = AboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    AboutRoute: AboutRoute,
    ContactRoute: ContactRoute,
    InsightsRoute: InsightsRoute,
    ProgrammeRoute: ProgrammeRoute,
    ScannerRoute: ScannerRoute,
    ServicesRoute: ServicesRoute,
    SuccessStoriesRoute: SuccessStoriesRoute,
    UseCasesRoute: UseCasesRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
